services:
  db:
    image: postgres:18.0
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      POSTGRES_DB: omatko_licznik
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    ports:
      - "5432:5432"
    volumes:
      - ./omatko-licznik_postgres_volume:/var/lib/postgresql/data

  front:
    depends_on:
      - backend
    container_name: front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      RUNNING_IN_CONTAINER: True
    depends_on:
      - db
    ports:
      - "5555:5555"
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front

secrets:
  db-password:
    file: db_password.txt
