version: '1'

services:

  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: zli_ludzie_na_omatko
      POSTGRES_DB: licznik_db

    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  front:
    depends_on:
      - backend
    container_name: front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production

  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5555:5555"

volumes:
  postgres_volume:
